#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define MAXLINE 120

int main (int argc, char **argv )
{
  FILE *infd, *outfd;
  char inname[50], outname[50];
  char line[MAXLINE];
  int size, rc, c;
  double avg, max, min, exectime, minexectime;
  char rest[12];
  double dsize;
  char line1[] ="#   bytes      mbyte/s      mbyte/s       mbyte/s        milli sec          milli sec";
  char line2[] = "#   mbytes     mbyte/s      mbyte/s       mbyte/s        milli sec         milli sec";


  if (argc != 3)
    {
      printf(" Usage : bTOmb <infilename> <outfilename>\n\n");
      printf(" This program converts the output generated by the latency"
	     " testsuite from Bytes to MBytes\n");
      exit ( 1 ) ;
    }

  strcpy ( inname, argv[1] );
  strcpy ( outname, argv[2] );

  infd  = fopen ( inname, "r" );
  outfd = fopen ( outname, "w" );


  while ( fscanf ( infd, "%[^\n]\n", line ) != EOF ) 
    {
      if ( line[0] == '#' ) {
	/* Skip comment lines, check however for the line,
	   which we have to replace */
	c = strncmp ( line, line1, sizeof(line1));
	if ( c == 0 )
	  fprintf ( outfd, "%s\n", line2 );
	else
	  fprintf ( outfd, "%s\n", line );

	continue;
      }

      /*read the parameters of the run */
      rc = sscanf ( line, "%d %lf %lf %lf %lf %lf %11s\n", 
		   &size, &avg, &min, &max, &exectime, &minexectime, rest );
      dsize = (double ) size;
      dsize = dsize / ( 1024 * 1024 );
      
      if ( rc == 7 ) 
	fprintf(outfd, "  %.8lf     %9.5lf     %9.5lf     %9.5lf     %.5lf   %.5lf %s\n", 
		dsize, avg, min, max, exectime, minexectime, rest ); 
      else
	fprintf(outfd, "  %.8lf     %9.5lf     %9.5lf     %9.5lf     %.5lf   %.5lf\n", 
		dsize, avg, min, max, exectime, minexectime ); 
      
    }

  fclose ( infd );
  fclose ( outfd );

  return ( 0 );
}
